### ISSUE TITLE
魔趣开源项目设备维护者邀请

### ISSUE THREAD

**Issue by martincz** [YumeMichi/kernel_oneplus_onyx#1]
Hi，我是魔趣的马丁龙猪，之前给你Gmail邮箱里发过消息，不知道你是否有看到。
看到你正在维护Oneplus X的Android Pie，所以想邀请你加入我们。
如果你有意向，可以和我联系。

**Comment by YumeMichi** [comment]
@martincz 这手机貌似都没什么人在用了 我还在维护这个基本是自己用（托腮

**Comment by martincz** [comment]
哈哈，没关系的。我们有很多已经上了9.0并且很老的机器，算是给用户多一点选择空间吧。
其实最重要的不是onyx是否适配魔趣，而是我们看到你一直在做，而且觉得你很棒，想邀请你加入我们，以后可以一起探讨技术、在适配中互相帮助什么的。
你要愿意的话加我QQ 445178647，我拉你进开发组。
